config/routes.rb
Rails.application.routes.draw do

  rutarel = ENV.fetch('RUTA_RELATIVA', '/')
  scope rutarel do 
    devise_scope :usuario do
      get 'sign_out' => 'devise/sessions#destroy'
      # El siguiente para superar mala generación del action en el formulario
      # cuando se autentica mal y esta montado no en / (genera 
      # /puntomontaje/puntomontaje/usuarios/sign_in )
      if (Rails.configuration.relative_url_root != '/') 
        ruta = File.join(Rails.configuration.relative_url_root, 
                         'usuarios/sign_in')
        post ruta, to: 'devise/sessions#create'
        get  ruta, to: 'devise/sessions#new'
      end
    end
    devise_for :usuarios, :skip => [:registrations], module: :devise
    as :usuario do
      get 'usuarios/edit' => 'devise/registrations#edit', 
        :as => 'editar_registro_usuario'    
      put 'usuarios/:id' => 'devise/registrations#update', 
        :as => 'registro_usuario'            
    end
    resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' } 

    post '/beneficiarios/unificar' => 'sip/personas#unificar',
      as: :beneficiarios_unificar
    get '/beneficiarios/unificar' => 'sip/personas#unificar',
      as: :beneficiarios_unificar_get
    get '/beneficiarios/deduplicar' => 'sip/personas#deduplicar',
      as: :beneficiarios_deduplicar
    get '/beneficiarios/repetidos' => 'sip/personas#reporterepetidos',
      as: :beneficiarios_repetidos
    post '/beneficiarios/repetidos' => 'sip/personas#reporterepetidos',
      as: :envia_beneficiarios_repetidas

    get 'beneficiarios/identificacionsd' => 'sip/personas#identificacionsd',
      as: :beneficiarios_identificacionsd

    post "/actos/agregar" => 'sivel2_sjr/actos#agregar',
      as: :actos_agregar
    get "/actos/eliminar" => 'sivel2_sjr/actos#eliminar',
      as: :actos_eliminar
    patch "/actos/agregarpr" => 'sivel2_sjr/actos#nuevopr',
      as: :actos_nuevopr

    # No se requiere edición
    resources :clavesrespaldos, path_names: { new: 'nueva' },
      controller: 'sip/clavesrespaldos'

    get "/conteos/accionesjuridicas" => 'sivel2_sjr/conteos#accionesjuridicas', 
      as: :conteos_accionesjuridicas
    get "/conteos/desplazamientos" => 'sivel2_sjr/conteos#desplazamientos', 
      as: :conteos_desplazamientos
    get "/conteos/municipios" => 'sivel2_sjr/conteos#municipios', 
      as: :conteos_municipios
    get "/conteos/rutas" => 'sivel2_sjr/conteos#rutas', 
      as: :contes_rutas
    get "/conteos/vacios" => 'sivel2_sjr/conteos#vacios',
      as: :conteos_vacios

    get '/migraciones/nuevo' => 'sivel2_sjr/migraciones#nuevo'  

    #get "/personas" => 'sip/personas#index'
    #get "/personas/remplazar" => 'sip/personas#remplazar'

    get "/casos/:id/fichaimp" => "sivel2_sjr/casos#fichaimp",
      as: :caso_fichaimp

    get "/casos/:id/fichapdf" => "sivel2_sjr/casos#fichapdf",
      as: :caso_fichapdf

    get "/casos/:id/solicitar" => "sivel2_sjr/casos#solicitar",
      as: :caso_solicitar

    get '/personas_casos' => 'sivel2_sjr/casos#personas_casos',
      as: :personas_casos

    get '/ubicacionespre' => 'sip/ubicacionespre#index',
      as: :ubicacionespre
    get '/ubicacionespre_mundep' => 'sip/ubicacionespre#mundep',
      as: :ubicacionespre_mundep
    get '/ubicacionespre_lugar' => 'sip/ubicacionespre#lugar',
      as: :ubicacionespre_lugar

    get '/actividadespf/nueva' => 'cor1440_gen/actividadespf#new',
      as: :nueva_actividadespf

    get '/actividadespf/:id' => 'cor1440_gen/actividadespf#show',
      as: :show_actividadespf

    get '/actividadespflistado' => 'cor1440_gen/actividadespf#index',
      as: :index_actividadespf

    get '/asistencia/rapidobenefcaso' =>
    'cor1440_gen/actividades#rapido_benef_caso', as: :rapido_benef_caso

    get '/consgifmm' => 'consgifmm#index',
      as: :consgifmm

    get '/detallesfinancieros/nuevo' => 'detallesfinancieros#nuevo'

    get '/revisaben_detalle' => 'cor1440_gen/actividades#revisaben_detalle'

    root "sip/hogar#index"

    namespace :admin do
      ab = ::Ability.new
      ab.tablasbasicas.each do |t|
        if (t[0] == "") 
          c = t[1].pluralize
          resources c.to_sym, 
            path_names: { new: 'nueva', edit: 'edita' }
        end
      end
    end
  end

  mount Sivel2Sjr::Engine, at: rutarel, as: 'sivel2_sjr'
  mount Sivel2Gen::Engine, at: rutarel, as: 'sivel2_gen'
  mount Cor1440Gen::Engine, at: rutarel, as: 'cor1440_gen'
  mount Sal7711Gen::Engine, at: rutarel, as: 'sal7711_gen'
  mount Mr519Gen::Engine, at: rutarel, as: 'mr519_gen'
  mount Heb412Gen::Engine, at: rutarel, as: 'heb412_gen'
  mount Sip::Engine, at: rutarel, as: 'sip'

end

app/models/sivel2_gen/acto.rb
require 'sivel2_sjr/concerns/models/acto'

class Sivel2Gen::Acto < ActiveRecord::Base
  include Sivel2Sjr::Concerns::Models::Acto

  has_one :actosjr, class_name: 'Sivel2Sjr::Actosjr',
    foreign_key: "id_acto", dependent: :delete, inverse_of: :acto
  accepts_nested_attributes_for :actosjr

end

app/models/sivel2_gen/anexo_victima.rb
module Sivel2Gen
  class AnexoVictima < ActiveRecord::Base

    include Sip::Modelo
    include Sip::Localizacion
    include Sip::FormatoFechaHelper

    belongs_to :victima, foreign_key: "victima_id", validate: true, 
      class_name: "Sivel2Gen::Victima", inverse_of: :anexo_victima, 
      optional: false
    belongs_to :sip_anexo, foreign_key: "anexo_id", validate: true, 
      class_name: "Sip::Anexo", optional: false
    accepts_nested_attributes_for :sip_anexo, reject_if: :all_blank


    campofecha_localizado :fecha

    validates :victima, presence: true
    validates :sip_anexo, presence: true
    validates :fecha, presence: true
  end
end

app/models/sivel2_gen/caso.rb
require 'sivel2_sjr/concerns/models/caso'
class Sivel2Gen::Caso < ActiveRecord::Base
  include Sivel2Sjr::Concerns::Models::Caso

  has_many :migracion, class_name: 'Sivel2Sjr::Migracion',
    foreign_key: "caso_id", validate: true, dependent: :destroy
  accepts_nested_attributes_for :migracion, allow_destroy: true, 
    reject_if: :all_blank

  def presenta(atr)
    case atr.to_s
    when 'fecharec'
      casosjr.fecharec if casosjr && casosjr.fecharec
    when 'oficina'
      casosjr.oficina.nombre if casosjr && casosjr.oficina
    when 'asesor'
      casosjr.usuario.nusuario if casosjr && casosjr.usuario
    when 'contacto'
      if casosjr && casosjr.contacto
        casosjr.contacto.nombres + ' ' + casosjr.contacto.apellidos +
       ' ' + ((casosjr.contacto.tdocumento.nil? ||
               casosjr.contacto.tdocumento.sigla.nil?) ? '' : 
              casosjr.contacto.tdocumento.sigla) + ' ' +
       ' ' + (casosjr.contacto.numerodocumento.nil? ? '' : 
              casosjr.contacto.numerodocumento)
      end
    when 'direccion'
      casosjr.direccion if casosjr && casosjr.direccion
    when 'telefono'
      casosjr.telefono if casosjr && casosjr.telefono
    else
      presenta_gen(atr) 
    end
  end

  validate :ppt_y_numero
  def ppt_y_numero
    migracion.each do |m|
      if m.fechasalida.nil?
        errors.add(:migracion, 
                   "En migración debe especificar fecha de salida")
      end
      if m.numppt && m.numppt.length>32 
        errors.add(:migracion, 
                   "Longitud del número ppt no puede exceder 32 caracteres")
      end
      if m.statusmigratorio_id.nil?
        errors.add(:migracion, 
                   "En migración debe especificar estatus migratorio")
      end
      if m.perfilmigracion_id.nil?
        errors.add(:migracion, 
                   "En migración debe especificar perfil de migración")
      end
      if m.pep && (m.numppt.nil? || m.numppt=='')
        errors.add(:migracion, 
                   "Si el migrante tiene PPT debe especificar el número")
      end
    end
  end

end

app/models/sivel2_gen/caso_solicitud.rb
require 'sivel2_gen/concerns/models/caso_solicitud'

module Sivel2Gen
  class CasoSolicitud < ActiveRecord::Base

    include Sivel2Gen::Concerns::Models::CasoSolicitud

    SER_ASESOR=1

    # Crea una solicitud predeterminada
    # Retorna mensaje de error si no lo logra o "" si lo logra
    def self.solicitar(remitente, codsol, caso_id, destinatarios)
      dsol = ""
      case codsol
      when SER_ASESOR
        dsol = "Ser asesor del caso #{caso_id}"
      end
      if dsol == ''
        return "codsol desconocido"
      end
      sol = Sip::Solicitud.create(
        usuario_id: remitente.id,
        fecha: Date.today,
        solicitud: dsol,
        estadosol_id: Sip::Solicitud::PENDIENTE
      );
      sol.usuarionotificar_ids = destinatarios.pluck(:id)
      sol.save
      Sivel2Gen::CasoSolicitud.create(
        solicitud_id: sol.id,
        caso_id: caso_id
      )
      return ""
    end

  end
end

app/models/sivel2_gen/categoria.rb
require 'sivel2_sjr/concerns/models/categoria'

class Sivel2Gen::Categoria < ActiveRecord::Base
  include Sivel2Sjr::Concerns::Models::Categoria
  
  has_and_belongs_to_many :desplazamiento, 
    class_name: 'Sivel2Sjr::Desplazamiento',
    foreign_key: :categoria_id, 
    association_foreign_key: "desplazamiento_id",
    join_table: 'sivel2_sjr_categoria_desplazamiento'

  has_many :causaRefugio, 
    class_name: 'Sivel2Sjr::Migracion',
    foreign_key: :causaRefugio_id

end

app/models/sivel2_gen/victima.rb
require 'sivel2_sjr/concerns/models/victima'

class Sivel2Gen::Victima < ActiveRecord::Base

  # Lo ponemos antes del include de Victima para que se ejecute antes
  before_destroy do
    Sivel2Sjr::Actosjr.where("id_acto IN (SELECT id FROM sivel2_gen_acto
                             WHERE id_caso=? AND id_persona=?)", 
                             id_caso, id_persona).delete_all
  end

  include Sivel2Sjr::Concerns::Models::Victima

  attr_accessor :rangoedadactual_id
  belongs_to :rangoedadactual, foreign_key: "rangoedadactual_id", 
    validate: true, class_name: "Sivel2Gen::Rangoedad", optional: true

  has_many :anexo_victima, foreign_key: 'victima_id', 
    validate: true, dependent: :destroy, 
    class_name: 'Sivel2Gen::AnexoVictima',
    inverse_of: :victima
  accepts_nested_attributes_for :anexo_victima, allow_destroy: true, 
    reject_if: :all_blank
  has_many :sip_anexo, :through => :anexo_victima, 
    class_name: 'Sip::Anexo'
  accepts_nested_attributes_for :sip_anexo,  reject_if: :all_blank

  #validates_associated :persona # Genera un mensaje demasiado simple: 
  # En 'Victima' no es válido 'Persona'

end

app/controllers/sivel2_gen/conteos_controller.rb
require 'sivel2_gen/concerns/controllers/conteos_controller'

module Sivel2Gen
  class ConteosController < ApplicationController

    # Autorización en cada función 
    include Sivel2Gen::Concerns::Controllers::ConteosController

  end
end

app/controllers/sivel2_gen/validarcasos_controller.rb
require 'sivel2_sjr/concerns/controllers/validarcasos_controller'

module Sivel2Gen
  class ValidarcasosController < ApplicationController


    load_and_authorize_resource class: Sivel2Gen::Caso
    include Sivel2Sjr::Concerns::Controllers::ValidarcasosController


    def validar_sin_derechovulnerado
      casos = ini_filtro
      casos = casos.joins('JOIN sivel2_sjr_respuesta ON
              sivel2_sjr_respuesta.id_caso=sivel2_sjr_casosjr.id_caso')
      validacion_estandar(
        casos, 
        'Casos con respuesta pero sin derecho vulnerado',
        'sivel2_sjr_respuesta.id NOT IN 
               (SELECT id_respuesta FROM public.sivel2_sjr_derecho_respuesta)'
      )
    end

    def validar_sin_casosjr
      casos = Sivel2Gen::Caso.order(:id)
      casos = filtro_fechas(casos, 'fecha')
      casos = filtro_etiqueta(casos)
      atr = ['sivel2_gen_caso.id', 
              'sivel2_gen_caso.fecha' ]
      encabezado = [
        'Código', 'Fecha de Desp. Emb.', 
        'Asesor']
      where = 'sivel2_gen_caso.id NOT IN 
           (SELECT id_caso FROM public.sivel2_sjr_casosjr) '
      titulo = 'Casos parcialmente eliminados'
      res = casos.where(where).select(atr)
      puts "validacion_estandar: res.to_sql=", res.to_sql
      arr = ActiveRecord::Base.connection.select_all(res.to_sql)
      @validaciones << { 
        titulo: titulo,
        encabezado: encabezado,
        cuerpo: arr 
      }
    end


    ## Sobrecarga una de sivel2_sjr 
    def valida_sinayudasjr
      casos = ini_filtro
      casos = casos.joins('JOIN sivel2_sjr_respuesta ON
              sivel2_sjr_respuesta.id_caso=sivel2_sjr_casosjr.id_caso')
      validacion_estandar(
        casos, 
        'Casos con respuesta/seguimiento pero sin respuesta del SJR',
        'sivel2_sjr_respuesta.id NOT IN 
           (SELECT id_respuesta FROM public.sivel2_sjr_ayudasjr_respuesta)
         AND sivel2_sjr_respuesta.id NOT IN 
           (SELECT id_respuesta FROM public.sivel2_sjr_aslegal_respuesta)
         AND sivel2_sjr_respuesta.id NOT IN 
           (SELECT id_respuesta FROM public.sivel2_sjr_motivosjr_respuesta)
        '
      )
    end

    def valida_nombres_beneficiarios_cortos
      reg = Sip::Persona.
        where('length(sip_persona.nombres) <= 2 OR '\
              'length(sip_persona.apellidos) <= 2')
      reg = filtro_fechas(reg, 'sip_persona.created_at')
      res = reg.
        order(:id).
        select([:id, :nombres, :apellidos, 
                '(SELECT sigla FROM sip_tdocumento WHERE sip_tdocumento.id=tdocumento_id LIMIT 1)', :numerodocumento,
                "array_to_string(array(SELECT DISTINCT id_caso FROM sivel2_gen_victima WHERE id_persona=sip_persona.id), ';') AS casos",
                "array_to_string(array(SELECT DISTINCT actividad_id FROM cor1440_gen_asistencia WHERE persona_id=sip_persona.id), ';') AS actividades"
        ])

      puts res.to_sql
      arr = ActiveRecord::Base.connection.select_all(res.to_sql)
      @validaciones << { 
        titulo: 'Beneficiarios con nombres o apellidos muy cortos',
        encabezado: ['Id', 'Nombres', 'Apellidos', 
                     'Tipo Doc.', 'Núm. Doc', 
                     'Caso(s)', 
                     'Actividad(es)'],
        cuerpo: arr 
      }
    end

    def validar_interno
      @rango_fechas = 'Fecha de recepción'
      valida_nombres_beneficiarios_cortos
      validar_sin_casosjr
      validar_sivel2_sjr
      validar_sin_derechovulnerado
      #validar_sivel2_gen
    end # def validar_interno
         
  end
end

app/views/sivel2_gen/casos/_filtro_mapaosm.html.erb
<div class= "row">
  <div class="col-sm-3">
    <input class= "campo-mapa-osm" name="num" type="hidden" value="200" />
    <div>
      <div>Fecha:</div>
      <div>
        <input type="text" 
               name="desde" 
               class="campo-mapa-osm form-control seleccion-mapa-osm"
               placeholder= "Desde" 
               id="campo-desde"
               data-behaviour="datepicker" 
               value="<%= Sip::FormatoFechaHelper::
                 fecha_estandar_local(@fechadesde) %>"
               size="11"/>
      </div>
      <div>
        <input type="text" 
               name="hasta" 
               class="campo-mapa-osm form-control seleccion-mapa-osm"
               placeholder= "Hasta" 
               id="campo-hasta"
               data-behaviour="datepicker" 
               value="<%= Sip::FormatoFechaHelper::
                 fecha_estandar_local(@fechahasta) %>"
               size="11"/>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
    <div>
      <div>Departamento:</div>
      <div>
        <select name="departamento" class="seleccion-mapa-osm form-control"
          id="departamento" style="width:140px;">
          <option value="0">Mostrar todos</option>
          <option value="">-----------------------</option>
          <%= options_for_select(Sip::Departamento.habilitados.where(id_pais: 170).all.collect { |d| [d.nombre, d.id ] })
        %> 
        </select>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
    <div>
      <div>Violencia:</div>
      <div>
        <select name="tvio" class="seleccion-mapa-osm form-control" id="tvio" style="width:150px;">
          <option value="0">Mostrar todos</option>
          <option value="">-----------------------</option>
          <%= options_for_select(Sivel2Gen::Categoria.all.collect { |d|
            [d.presenta_con_codigo, d.id ] }.sort)%>
        </select>
      </div>
    </div>
  </div>
</div>

app/views/sivel2_gen/casos/_index_mas_acciones.html.erb
<% if current_usuario && 
     [Ability::ROLADMIN, Ability::ROLDIR,
      Ability::ROLCOOR, Ability::ROLANALI, 
      Ability::ROLSIST].include?(current_usuario.rol) && 
     !can?(:edit, Sivel2Gen::Caso.find(caso.caso_id)) %>
   <%= link_to('Solicitar', main_app.caso_solicitar_path(caso.caso_id), class: 'btn btn-sm') %>
 <% end %>

app/views/sivel2_gen/casos/_show_asesorhistorico.html.erb
<table class="table table-bordered table-sm">
  <thead class="thead-light">
    <tr>
      <th>Asesor</th>
      <th>Oficina</th>
      <th>Fecha Inicial</th>
      <th>Fecha Final</th>
    </tr>
  </thead>
  <tbody>
    <% if @caso.casosjr %>
      <% @caso.casosjr.asesorhistorico.order(fechainicio: :desc, id: :desc).each do |ah| %>
        <tr>
          <td> <%= ah.usuario.nusuario %></td>
          <td> <%= ah.oficina.nombre if ah.oficina %></td>
          <td> <%= ah.fechainicio_localizada %> </td>
          <td> <%= ah.fechafin_localizada %> </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/sivel2_gen/casos/_show_atenciones.html.erb
<dl>
  <dt>Atención/es en las que alguna persona de este caso es beneficiaria:</dt>

  <dd>
    <%= render partial: 'sivel2_gen/casos/tabla_atenciones' %>
   </dd>
</dl>

app/views/sivel2_gen/casos/_show_etiqueta_ids.html.erb
<%= render partial: '/sip/personas/tabla_etiqueta_x', locals: {relacion: :caso_etiqueta} %>

app/views/sivel2_gen/casos/_show_listado_anexos.html.erb
<table class="tablalistadovictima table table-striped  table-bordered table-sm ">
  <thead class="thead-light">
    <tr>
      <th>Fecha</th>
      <th>Descripción</th>
      <th>Enlace de descarga</th>
    </tr>
  </thead>
  <tbody id="victima">
    <% anexosids = Sivel2Gen::Caso.find(@registro.id).anexo_caso.pluck(:id_anexo) %>
    <% anexos = Sip::Anexo.find(anexosids)%>
    <% anexos.each do |anexo| %>
      <tr>
        <td>
          <%= Sivel2Gen::AnexoCaso.where(id_anexo: anexo.id)[0].fecha if 
          Sivel2Gen::AnexoCaso.where(id_anexo: anexo.id)[0] %>
        </td>
        <td>
          <%= anexo.descripcion if anexo.descripcion %>
        </td>
        <td>
          <a href="<%= sip.descarga_anexo_path(anexo.id) %>", style="text-decoration:none" data-turbo='false'><%= anexo.adjunto_file_name %></a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sivel2_gen/casos/_show_listado_familiares.html.erb
<table class="tablalistadovictima table table-striped  table-bordered table-sm  ">
  <thead class="thead-light">
    <tr>
      <th colspan="2">Nombre</th>
      <th colspan="2">Identificación</th>
      <th>Relación con contacto</th>
    </tr>
  </thead>
  <tbody id="victima">
    <% @registro.victima.each do |victima| %>
      <tr>
        <td>
          <%= victima.persona.nombres if victima.persona.nombres %>
        </td>
        <td>
          <%= victima.persona.apellidos if victima.persona.apellidos %>
        </td>
        <td>
          <%= victima.persona.tdocumento.sigla if victima.persona.tdocumento%>
        </td>
        <td>
          <%= victima.persona.numerodocumento if victima.persona.numerodocumento %>
        </td>
        <td>
          <% if @registro.casosjr.contacto_id.to_i != victima.persona.id %>
            <%= Sivel2Sjr::Victimasjr.find(victima.id).rolfamilia.nombre if 
            Sivel2Sjr::Victimasjr.find(victima.id).rolfamilia %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sivel2_gen/casos/_show_solicitudes.html.erb
<%= render partial: 'sip/solicitudes/resumen_tabla_solicitudes',
  locals: { objeto: @caso } %>

app/views/sivel2_gen/casos/_tabla_atenciones.html.erb
<% ga4 = Cor1440Gen::Actividad.
  joins(
    'INNER JOIN cor1440_gen_asistencia '\
    'ON cor1440_gen_asistencia.actividad_id = cor1440_gen_actividad.id'
  ).where(
    'cor1440_gen_asistencia.persona_id IN '\
    '(SELECT id_persona FROM sivel2_gen_victima WHERE '\
      '  sivel2_gen_victima.id_caso=?)', 
     @caso.id
  ) 
%>
<table style="width: 100%" class="table table-striped table-bordered">
  <thead class="thead-light">
    <tr>
      <th>Actividad</th>
      <th>Fecha de Atención</th>
      <th>Nombre de la actividad</th>
      <th>Convenio Financiador</th>
      <th>Beneficiario/a de este caso</th>
    </tr>
  </thead>
  <tbody>
    <% ga4.order(
      ['cor1440_gen_actividad.fecha DESC', 
       'cor1440_gen_actividad.id DESC']).pluck(:id).uniq.each  do |acid| %>
       <% g = Cor1440Gen::Actividad.find(acid) %>
       <tr>
         <td>
           <%= link_to g.id.to_s,
             cor1440_gen.actividad_path(g),
             target: '_blank' %>
         </td>
         <td><%= g.fecha %></td>
         <td><%= g.nombre %></td>
         <td>
           <% pfs= [] %>
           <% pfs = g.proyectofinanciero_ids.uniq - [10] %>
           <% if pfs != [] %>
             <% convenio = pfs.inject('') {|memo, p| 
               pf = Cor1440Gen::Proyectofinanciero.find(p)
               memo == '' ? pf.nombre : memo + '; ' + pf.nombre } %>
           <% end %>
           <%= convenio %>
         </td>
         <td>
           <%= ga4.where(id: acid).
             pluck('cor1440_gen_asistencia.persona_id').
             map { |idp| Sip::Persona.find(idp).presenta_nombre }.
             join(". ") %>
         </td>
       </tr>
     <% end %>
  </tbody>
</table>